import HomeScreen as hs
# import NewUserRegistration as nur
import PasswordRecovery as pr
import ToDoList as td 

def Removemain():
	hs.label1.grid_forget()
	hs.label2.place_forget()
	hs.label3.place_forget()
	hs.label4.place_forget()
	hs.label5.place_forget()
	hs.button1.place_forget()
	hs.button2.place_forget()
	hs.button3.place_forget()
	hs.entry1.place_forget()
	hs.entry2.place_forget()

def ClearNewUser():
	nur.labelNU.grid_forget()
	nur.labelNU1.place_forget()
	nur.labelNU2.place_forget()
	nur.labelNU3.place_forget()
	nur.labelNU4.place_forget()
	nur.labelNU5.place_forget()
	nur.labelNU6.place_forget()
	nur.labelNU7.place_forget()
	nur.labelNU8.place_forget()
	nur.entryNU1.place_forget()
	nur.entryNU2.place_forget()
	nur.entryNU3.place_forget()
	nur.cal.place_forget()
	nur.entryNU5.place_forget()
	nur.entryNU6.place_forget()
	nur.entryNU8.place_forget()
	nur.buttonNU1.place_forget()
	nur.buttonNU2.place_forget()
	nur.drop.place_forget()

def ClearForgotPassword():
	pr.label1.grid_forget()
	pr.label2.place_forget()
	pr.label3.place_forget()
	pr.label4.place_forget()
	pr.label5.place_forget()
	pr.label6.place_forget()
	pr.entry1.place_forget()
	pr.entry2.place_forget()
	pr.cal.place_forget()
	pr.button1.place_forget()
	pr.button2.place_forget()

def ClearOTP():
	pr.labelA.grid_forget()
	pr.labelB.place_forget()
	pr.labelC.place_forget()
	pr.labelD.place_forget()
	pr.labelE.place_forget()
	pr.entryA.place_forget()
	pr.entryB.place_forget()
	pr.entryC.place_forget()
	pr.buttonA.place_forget()
	pr.buttonB.place_forget()

def ClearResetPassword():
	pr.label1A.grid_forget()
	pr.label1B.place_forget()
	pr.label1C.place_forget()
	pr.label1D.place_forget()
	pr.label1E.place_forget()
	pr.label1F.place_forget()
	pr.label1G.place_forget()
	pr.entry1B.place_forget()
	pr.entry1C.place_forget()
	pr.entry1D.place_forget()
	pr.entry1E.place_forget()
	pr.entry1F.place_forget()
	pr.entry1G.place_forget()
	pr.button1A.place_forget()
	pr.button1B.place_forget()

def ClearTodoList():
	td.label1.grid_forget()
	td.label2.place_forget()
	td.label3.place_forget()
	td.label4.place_forget()
	td.button1.place_forget()
	td.button2.place_forget()
	td.button3.place_forget()
	td.button4.place_forget()
	td.button5.place_forget()
	td.treev.place_forget()
	td.vsb.place_forget()
